name: Test, Buid

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  SolutionName: ${{github.event.repository.name}}

jobs:
  test_net_ubuntu:
    name: Testing .NET (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Testing .NET
      run: dotnet test PushSharp.Tests\PushSharp.Tests.csproj --verbosity normal --configuration Release

  build_net_framework:
    name: Building .NET Framework assemblies
    needs: [test_net_ubuntu]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Restoring NuGet packages
      run: nuget restore "${{github.workspace}}\${{env.SolutionName}}.sln"
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
    - name: Build solution
      run: msbuild ${{env.SolutionName}}.sln /property:Configuration=Release -property:SignAssembly=false -property:OutputPath="${{github.workspace}}/bin/"