name: Test, Buid

on:
  workflow_dispatch:

  pull_request:
    branches: [ "master" ]

env:
  SolutionName: ${{github.event.repository.name}}

jobs:
  build_net_framework:
    name: Building .NET Framework assemblies
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Restoring NuGet packages
      run: nuget restore "${{github.workspace}}\${{env.SolutionName}}.sln"
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
    - name: Build solution
      run: msbuild ${{env.SolutionName}}.sln /property:Configuration=Release -property:SignAssembly=false -property:OutputPath="${{github.workspace}}/bin/"